name: example
description: A sample command-line application.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  cell:
    path: ../cell
  collection: ^1.18.0
  equatable: ^2.0.5
  ffi: ^2.1.0
  meta: ^1.11.0
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner:
  cell_generator:
    path: ../generator
